remote_theme: christianezeani/panthera-jekyll

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Panthera-Jekyll
subtitle: Full-Stack Developer

# Side menu
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: Skills & Offers
    link: /skills-and-offers
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

# Social links
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter

  - name: rubygem
    link: https://rubygems.org/profiles/christianezeani
    icon: fas fa-gem


    
